// <auto-generated />
namespace Valtech_Task3_Ankh_Morpork_MVC_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameColoumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameColoumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202112151619357_RenameColoumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
